### ISSUE TITLE
Support non-interactive mode

### ISSUE THREAD

**Issue by tbinna** [ServiceRocket/sbt-git-flow#1]
To use this plugin on build servers it would be nice to support a non-interactive mode that does not ask for the confirmation of version numbers.

**Comment by naderghanbari** [comment]
This plugin is relying on the `release` plugin, so by using the `sbt 'release with-defaults'` command the defaults will be used so no user interaction is needed. 

Let me know if this covers your case and I'll add a brief instruction about this to the `README` file.

**Comment by naderghanbari** [comment]
PR merged: https://github.com/ServiceRocket/sbt-git-flow/pull/3
